# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup-dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: restore-dependencies
      run: dotnet restore
    - name: build
      run: dotnet build --no-restore --output ./bin -m
    - name: test
      run: dotnet test --no-build --verbosity normal --output ./bin
    - name: package-generated-files
      run: |
            pwd
            cd ./bin
            zip -r ./../asset.zip ./*
            pwd
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get-current-time
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: create-release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}-${{ env.CURRENT_DATE }}
          release_name: Release ${{ github.ref_name }}-${{ env.CURRENT_DATE }}
          draft: false
          prerelease: false
      - name: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: asset.zip
          asset_path: ./asset.zip
          asset_content_type: application/zip
